### PR TITLE
Add my upcoming event

### LINKED ISSUE #18: 🚀 [New Contribution]: Demystifying Hacktoberfest
**Describe Your Contribution Here**
This is a blog on guide to Markdown files. Markdown files are an important part to write docs for any open source projects.

I want to add it to this repo as part of Showwcase Hacktoberfest contribution.

Show link:- https://www.showwcase.com/show/17620/a-complete-guide-for-markdown-files

### PR DESCRIPTION
**Pull request by Susmita-Dey**
Closes issue #18 

Kindly review and merge this PR

### CODE REVIEW

**Review by atapas — APPROVED** [review]
@Susmita-Dey Thanks

**Review by atapas — CHANGES_REQUESTED** [review]
@Susmita-Dey Can you please check this... I am not able to merge

image

**Comment by Susmita-Dey** [comment]
> image

It's also visible to me but I can't see any kind of conflicts in my file.

**Comment by Susmita-Dey** [comment]
@atapas It closed automatically. Not showing as merged. What happened here?

**Comment by Susmita-Dey** [comment]
Got merged and closed. Not showing the merged icon on the top.

**Comment by atapas** [comment]
How is this happened!!! I'm wondering.

**Comment by Susmita-Dey** [comment]
Will you be reverting the PR so that I can make one?

Or shall I leave as it is.

Let me know @atapas

**Pull request closed without merging**
